services:
  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "fastapi_restaurant"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 15s
      retries: 3

  fastapiapp:
    container_name: fastapiapp
    restart: always
    build: 
      context: ./
      dockerfile: dockerfile
    environment:
      DB_USER: "postgres"
      DB_PASSWD: "postgres"
      DB_HOST: db
      DB_PORT: 5433
      DB_NAME: "fastapi_restaurant"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data: